package vista;

import java.awt.Color;
import javax.swing.ImageIcon; 


public class PanelResultado extends javax.swing.JPanel {

    
    public PanelResultado() {
        initComponents();
    }


public void cambiarTema(boolean esOscuro) {
    Color fondoPanel, colorTexto;

    if (esOscuro) {
        
        fondoPanel = new Color(60, 63, 65);
        colorTexto = Color.WHITE;
    } else {
       
        fondoPanel = new Color(214, 214, 209); 
        colorTexto = Color.BLACK;
    }

    jPanel1.setBackground(fondoPanel);
    Label_Resultado.setForeground(colorTexto);
    
   
    mostrarNumero(0); 
}
public void mostrarGanador(String idGanador) {
    Label_Resultado.setText("¡BINGO!");
    Label_Resultado.setForeground(Color.RED);
    
}
    
    public void mostrarNumero(int numero) {
        if (numero >= 1 && numero <= 75) {
            Label_Resultado.setText(String.valueOf(numero));
            Label_Resultado.setIcon(null); 
        } else {
            
            Label_Resultado.setText("-"); 
            Label_Resultado.setIcon(null);
        }
    }
    
    
    public void mostrarGanador(boolean esGanador) {
        if (esGanador) {
            
            Label_Resultado.setText("BINGO!");
            
             Label_Resultado.setForeground(Color.RED);
           
        } else {
           
            mostrarNumero(0); 
          
             Label_Resultado.setForeground(Color.BLACK); 
        }
    }

public void mostrarIconoBingoWin() {
    try {
        
        ImageIcon icono = new ImageIcon(getClass().getResource("recursos/BingoWin.png"));
        
        
        Label_Resultado.setIcon(icono);
        
        
        Label_Resultado.setText(""); 
        
       
        Label_Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Resultado.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        
    } catch (Exception e) {
       
        System.err.println("No se pudo cargar la imagen BingoWin.png. Revise la ruta /recursos/BingoWin.png. Error: " + e.getMessage());
        Label_Resultado.setText("¡WIN!");
        Label_Resultado.setIcon(null);
    }
    
    this.revalidate();
    this.repaint();
}
public void limpiarGanador() {
    Label_Resultado.setText("0"); 
    
}
public void generarNumeroAleatorioConEspera() {
    
    int numeroAleatorio = (int) (Math.random() * 76); 
    
 
    mostrarNumero(numeroAleatorio);
    
   
    javax.swing.Timer timer = new javax.swing.Timer(3000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
         
            mostrarNumero(0); 
        }
    });
    
     
    timer.setRepeats(false);
    timer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Resultado = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(214, 214, 209));

        Label_Resultado.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        Label_Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Resultado.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(Label_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Label_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Resultado;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}